-- Enable UUID extension (optional, but good practice if we switched to UUIDs, but keeping Integers to match existing logic for now)
-- create extension if not exists "uuid-ossp";
-- 1. Users Table
create table public.users (
  id bigint generated by default as identity primary key,
  telegram_id bigint not null unique,
  name text,
  github_username text,
  linkedin_url text,
  portfolio_url text,
  email text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);
-- 2. Readme Sessions Table
create table public.readme_sessions (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade not null,
  raw_input_text text,
  structured_data jsonb,
  generated_readme text,
  status text default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  completed_at timestamp with time zone
);
-- 3. User Skills Table
create table public.user_skills (
  id bigint generated by default as identity primary key,
  session_id bigint references public.readme_sessions(id) on delete cascade not null,
  skill_name text not null,
  category text,
  has_icon boolean default false
);
-- 4. Ratings Table
create table public.ratings (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade not null,
  session_id bigint references public.readme_sessions(id) on delete set null,
  stars integer not null,
  feedback_text text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
-- Enable Row Level Security (RLS) - Optional for now if using Service Role key, 
-- but recommended if you ever use Client Key on frontend.
alter table public.users enable row level security;
alter table public.readme_sessions enable row level security;
alter table public.user_skills enable row level security;
alter table public.ratings enable row level security;
-- Open access policies (Simplest for bot usage if not using Service Key, BUT Service Key is better)
-- Ideally, don't run these if you use the Service Role Key. 
-- If you only have the Anon key and need to write, you might need these (INSECURE for public web apps, fine for a private bot connection)
create policy "Enable all access for all users" on public.users for all using (true) with check (true);
create policy "Enable all access for all users" on public.readme_sessions for all using (true) with check (true);
create policy "Enable all access for all users" on public.user_skills for all using (true) with check (true);
create policy "Enable all access for all users" on public.ratings for all using (true) with check (true);
