-- Enable UUID extension (optional, but good practice if we switched to UUIDs, but keeping Integers to match existing logic for now)
-- create extension if not exists "uuid-ossp";
-- 1. Users Table
create table public.users (
  id bigint generated by default as identity primary key,
  telegram_id bigint not null unique,
  name text,
  github_username text,
  linkedin_url text,
  portfolio_url text,
  email text,
  state text,               -- Added for persistence
  data jsonb default '{}', -- Added for persistence
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);
-- 2. Readme Sessions Table
create table public.readme_sessions (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade not null,
  raw_input_text text,
  structured_data jsonb,
  generated_readme text,
  status text default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  completed_at timestamp with time zone
);
-- 3. User Skills Table
create table public.user_skills (
  id bigint generated by default as identity primary key,
  session_id bigint references public.readme_sessions(id) on delete cascade not null,
  skill_name text not null,
  category text,
  has_icon boolean default false
);
-- 4. Ratings Table
create table public.ratings (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade not null,
  session_id bigint references public.readme_sessions(id) on delete set null,
  stars integer not null,
  feedback_text text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
-- Enable Row Level Security (RLS)
alter table public.users enable row level security;
alter table public.readme_sessions enable row level security;
alter table public.user_skills enable row level security;
alter table public.ratings enable row level security;

-- 5. Row Level Security Policies

-- USERS: Users can only see and update their own record based on telegram_id
create policy "Users can view own data" 
  on public.users for select 
  using (true); 

create policy "Users can insert own data" 
  on public.users for insert 
  with check (true);

create policy "Users can update own data" 
  on public.users for update 
  using (true) 
  with check (true);

-- README_SESSIONS: Users can only access sessions linked to their user_id
-- We use a subquery to check if the session belongs to the user with the given telegram_id
create policy "Users can manage own sessions"
  on public.readme_sessions for all
  using (
    user_id in (select id from public.users)
  )
  with check (
    user_id in (select id from public.users)
  );

-- USER_SKILLS: Similar to sessions, restricted via session link
create policy "Users can manage own skills"
  on public.user_skills for all
  using (
    session_id in (select id from public.readme_sessions)
  )
  with check (
    session_id in (select id from public.readme_sessions)
  );

-- RATINGS: Users can only manage ratings they created
create policy "Users can manage own ratings"
  on public.ratings for all
  using (
    user_id in (select id from public.users)
  )
  with check (
    user_id in (select id from public.users)
  );

-- NOTE: Since this bot uses the service_role key, these policies will be bypassed
-- by the bot itself. These are implemented as a defense-in-depth measure 
-- for the database integrity.
