"""
GitHub API Service
Handles interactions with GitHub API for auto-deployment
"""

import httpx
import base64
from typing import Optional, Dict, Any, List
from utils.logger import Logger

logger = Logger.get_logger(__name__)

class GitHubAPI:
    """Service for interacting with GitHub API"""
    
    BASE_URL = "https://api.github.com"
    
    def __init__(self, token: str):
        self.token = token
        self.headers = {
            "Authorization": f"token {token}",
            "Accept": "application/vnd.github.v3+json",
            "User-Agent": "GitHub-Readme-Bot"
        }
    
    async def validate_token(self) -> Optional[str]:
        """
        Validate the token and return the username
        Returns username if valid, None otherwise
        """
        async with httpx.AsyncClient() as client:
            try:
                response = await client.get(
                    f"{self.BASE_URL}/user",
                    headers=self.headers
                )
                
                if response.status_code == 200:
                    data = response.json()
                    return data.get("login")
                
                logger.warning(f"Token validation failed: {response.status_code} - {response.text}")
                return None
            except Exception as e:
                logger.error(f"Error validating token: {e}")
                return None
    
    async def get_repo(self, username: str, repo_name: str) -> Optional[Dict[str, Any]]:
        """Get repository details if it exists"""
        async with httpx.AsyncClient() as client:
            try:
                response = await client.get(
                    f"{self.BASE_URL}/repos/{username}/{repo_name}",
                    headers=self.headers
                )
                
                if response.status_code == 200:
                    return response.json()
                return None
            except Exception as e:
                logger.error(f"Error getting repo: {e}")
                return None

    async def create_repo(self, repo_name: str, description: str = None, private: bool = False) -> bool:
        """Create a new repository"""
        async with httpx.AsyncClient() as client:
            try:
                payload = {
                    "name": repo_name,
                    "description": description or "Generated by GitHub Profile Bot",
                    "private": private,
                    "auto_init": True
                }
                
                response = await client.post(
                    f"{self.BASE_URL}/user/repos",
                    headers=self.headers,
                    json=payload
                )
                
                if response.status_code in [201, 200]:
                    return True
                
                logger.error(f"Failed to create repo: {response.status_code} - {response.text}")
                return False
            except Exception as e:
                logger.error(f"Error creating repo: {e}")
                return False

    async def update_file(self, username: str, repo_name: str, path: str, content: str, message: str) -> bool:
        """Create or update a file in the repository"""
        async with httpx.AsyncClient() as client:
            try:
                # First check if file exists to get sha
                url = f"{self.BASE_URL}/repos/{username}/{repo_name}/contents/{path}"
                enc_content = base64.b64encode(content.encode()).decode()
                
                payload = {
                    "message": message,
                    "content": enc_content
                }
                
                # Check for existing file
                get_response = await client.get(url, headers=self.headers)
                if get_response.status_code == 200:
                    sha = get_response.json().get("sha")
                    payload["sha"] = sha
                
                # Create/Update file
                response = await client.put(url, headers=self.headers, json=payload)
                
                if response.status_code in [200, 201]:
                    return True
                
                logger.error(f"Failed to update file {path}: {response.status_code} - {response.text}")
                return False
            except Exception as e:
                logger.error(f"Error updating file {path}: {e}")
                return False

    async def enable_actions(self, username: str, repo_name: str) -> bool:
        """
        Enable GitHub Actions for the repository
        Note: The API doesn't have a direct endpoint to 'enable' actions if disabled by default setting,
        but creating a workflow usually triggers it. 
        We can check workflows permissions if needed.
        """
        # Usually creating the .github/workflows/snake.yml is enough
        return True

    async def trigger_workflow(self, username: str, repo_name: str, workflow_file: str) -> bool:
        """Trigger a workflow dispatch event"""
        async with httpx.AsyncClient() as client:
            try:
                url = f"{self.BASE_URL}/repos/{username}/{repo_name}/actions/workflows/{workflow_file}/dispatches"
                payload = {"ref": "main"}  # Adjust branch if needed
                
                response = await client.post(url, headers=self.headers, json=payload)
                
                if response.status_code == 204:
                    return True
                
                logger.error(f"Failed to trigger workflow: {response.status_code} - {response.text}")
                return False
            except Exception as e:
                logger.error(f"Error triggering workflow: {e}")
                return False
